### ISSUE TITLE
Cann't see keyboard shortcut information when cmd+shift+p

### ISSUE THREAD

**Issue by Bladefidz** [atom/atom-light-ui#24]
![screenshot from 2015-07-11 20 23 55](https://cloud.githubusercontent.com/assets/7363223/8633882/3023ea66-280b-11e5-8344-14a4063c2ff4.png)

**Comment by mnquintana** [comment]
What version of Atom are you using?

**Comment by 50Wliu** [comment]
Yeah, this should definitely be fixed in the latest Atom version (currently 1.0.2).

**Comment by Bladefidz** [comment]
Oh no, i am still using 0.201.0 right now. I didn't know atom not support self auto update.

**Comment by 50Wliu** [comment]
> Oh no, i am still using 0.201.0 right now. I didn't know atom not support self auto update.

Atom on Linux currently doesn't auto-update, sorry about that :(.  You can get the latest .deb/.rpm download [here](https://github.com/atom/atom/releases).
