### ISSUE TITLE
Cannot publish fork as a theme on to atom.io

### ISSUE THREAD

**Issue by ThanatchaPanpairoj** [atom/atom-light-ui#25]
Hi, recently, I followed the instructions to create a theme by forking from an existing one. I created a fork of this repo, cloned it, and then changed the theme colors in uivariables.less and treeview.less.

I also renamed the repo and the local file and changed the .json file to this:
{
  "name": "atom-soft-green-ui",
  "theme": "ui",
  "version": "0.42.0",
  "description": "A soft green UI theme for Atom",
  "repository": "https://github.com/ThanatchaPanpairoj/atom-soft-green-ui.git",
  "license": "MIT",
  "engines": {
    "atom": ">0.50.0"
  }
}

After I was done, I committed the changes to master and synced. Then, I did an apm publish minor and I got this:
Registering atom-soft-green-ui done
Preparing and taggin a new version done
Pushing v0.43.0 tag failed

It's published but listed as a package on https://atom.io/users/ThanatchaPanpairoj However, I am trying to publish it as a theme.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/apm? Thanks!

**Comment by ThanatchaPanpairoj** [comment]
Okay here it is: https://github.com/atom/apm/issues/404
Sorry for posting at the wrong place.
